version: '3'
services:
  todolist:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - DB_PORT=3306
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=1234
      - DB_NAME=todos
    depends_on:
      - db

  db:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: todos
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - volume-mysql:/var/lib/mysql

volumes:
  volume-mysql:
    external: true ## 기존 존재하는 볼륨을 사용함
